---
apiVersion: v1
kind: Service
metadata:
  labels: {}
  name: flux
  namespace: flux
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 3030
    targetPort: http
    protocol: TCP
  selector:
    name: flux
