apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - image-reflector-controller.sa.yaml
  - image-reflector-controller.crds.yaml
  - image-reflector-controller.deployment.yaml
  #- https://github.com/fluxcd/image-reflector-controller/releases/download/v0.13.0/image-reflector-controller.crds.yaml
  #- https://github.com/fluxcd/image-reflector-controller/releases/download/v0.13.0/image-reflector-controller.deployment.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: image-reflector-controller
  path: ./patches/image-reflector-controller-patch.yaml
