apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - image-automation-controller.sa.yaml
  - image-automation-controller.crds.yaml
  - image-automation-controller.deployment.yaml
  #- https://github.com/fluxcd/image-automation-controller/releases/download/v0.14.1/image-automation-controller.crds.yaml
  #- https://github.com/fluxcd/image-automation-controller/releases/download/v0.14.1/image-automation-controller.deployment.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: image-automation-controller
  path: ./patches/image-automation-controller-patch.yaml
