---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: basic-web-lighttpd
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: basic-web-lighttpd
  filterTags:
    pattern: 'latest'
  policy:
    alphabetical:
      order: asc

