---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: my-eks-cluster
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: https://github.com/dnlloyd/my-eks-cluster

