apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - notification-controller.sa.yaml
  - notification-controller.crds.yaml
  - notification-controller.deployment.yaml
  #- https://github.com/fluxcd/notification-controller/releases/download/v0.16.0/notification-controller.crds.yaml
  #- https://github.com/fluxcd/notification-controller/releases/download/v0.16.0/notification-controller.deployment.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: notification-controller
  path: ./patches/notification-controller-patch.yaml
