apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - source-controller.sa.yaml
  - source-controller.crds.yaml
  - source-controller.deployment.yaml
  #- https://github.com/fluxcd/source-controller/releases/download/v0.15.4/source-controller.crds.yaml
  #- https://github.com/fluxcd/source-controller/releases/download/v0.15.4/source-controller.deployment.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: source-controller
  path: ./patches/source-controller-patch.yaml
