apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: web2
  name: web2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web2
  minReadySeconds: 5
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web2
    spec:
      containers:
      - image: dnlloyd/basic-web-lighttpd:0.1.0 # {"$imagepolicy": "flux-system:basic-web-lighttpd"}
        name: web2
