---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-web
  namespace: flux-system
  annotations:
    ann: yes-please
spec:
  interval: 1m0s
  path: ./apps/web
  prune: true
  sourceRef:
    kind: GitRepository
    name: my-eks-cluster
  targetNamespace: web

