# memcached deployment used by Flux to cache
# container image metadata.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels: {}
  name: flux-memcached
  namespace: flux
spec:
  replicas: 1
  selector:
    matchLabels:
      name: flux-memcached
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: flux-memcached
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
      containers:
      - args:
        - -m 512    # Maximum memory to use, in megabytes. 64MB is default.
        - -p 11211  # Default port, but being explicit is nice.
        - -I 5m     #  Maximum size for one item
        image: memcached:1.5.20
        imagePullPolicy: IfNotPresent

        name: memcached
        ports:
        - name: clients
          containerPort: 11211
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          runAsUser: 11211
          runAsGroup: 11211
          allowPrivilegeEscalation: false
