---
apiVersion: v1
kind: Service
metadata:
  labels: {}
  name: flux-memcached
  namespace: flux
spec:
  type: ClusterIP
  ports:
  - name: memcached
    port: 11211
    targetPort: clients
    protocol: TCP
  selector:
    name: flux-memcached
