apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
  - helm-controller.sa.yaml
  - helm-controller.crds.yaml
  - helm-controller.deployment.yaml
  #- https://github.com/fluxcd/helm-controller/releases/download/v0.12.1/helm-controller.crds.yaml
  #- https://github.com/fluxcd/helm-controller/releases/download/v0.12.1/helm-controller.deployment.yaml

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: helm-controller
  path: ./patches/helm-controller-patch.yaml
